// @vitest-environment jsdom

import { act } from 'react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, Route, Routes } from 'react-router-dom'

const fetchSessionMock = vi.fn()
const fetchSessionTraceMock = vi.fn()

vi.mock('../src/lib/api/ops', () => ({
  fetchSession: fetchSessionMock,
  fetchSessionTrace: fetchSessionTraceMock,
  getApiErrorMessage: (_error: unknown, fallback: string) => fallback,
}))

vi.mock('../src/hooks/useI18n', () => ({
  useI18n: () => ({
    t: (key: string, paramsOrFallback?: Record<string, unknown> | string) => {
      const fallback = typeof paramsOrFallback === 'string' ? paramsOrFallback : undefined
      const params = typeof paramsOrFallback === 'object' ? paramsOrFallback : undefined
      const table: Record<string, string> = {
        'nav.sessions': 'Sessions',
        'common.service': 'Service',
        'common.host': 'Host',
        'common.na': 'n/a',
        'sessions.loading': 'Loading diagnosis workbench...',
        'sessions.notFound': 'Session not found.',
        'sessions.error.load': 'Unable to load session.',
        'sessions.backToQueue': 'Back to queue',
        'sessions.action.reviewApprovals': 'Review approvals',
        'sessions.sections.currentDiagnosis': 'Current diagnosis',
        'sessions.sections.currentDiagnosisDesc': 'Lead with the operator-facing call, evidence, risk, next step, and current state.',
        'sessions.sections.evidenceSummary': 'Evidence summary',
        'sessions.sections.evidenceSummaryDesc': 'Show the strongest metrics, logs, and traces signals before the raw process.',
        'sessions.sections.narrative': 'Diagnosis narrative',
        'sessions.sections.narrativeDesc': 'Narrative stays available after the first-screen summary.',
        'sessions.sections.toolPlan': 'Tool plan',
        'sessions.sections.toolPlanDesc': 'Recorded execution chain and evidence collection steps.',
        'sessions.sections.attachments': 'Evidence attachments',
        'sessions.sections.attachmentsDesc': 'Images, files, and previews captured in the session thread.',
        'sessions.sections.knowledge': 'Knowledge context',
        'sessions.sections.knowledgeDesc': 'Materialized knowledge and related context used during diagnosis.',
        'sessions.sections.rawContext': 'Raw alert context',
        'sessions.sections.rawContextDesc': 'Fallback low-level payload when the operator needs the original event.',
        'sessions.sections.verification': 'Verification',
        'sessions.sections.verificationDesc': 'Post-action verification summary returned by the backend.',
        'sessions.sections.notifications': 'Notifications',
        'sessions.sections.notificationsDesc': 'Why this session notified someone, where it went, and when.',
        'sessions.sections.linkedExecutions': 'Linked executions',
        'sessions.sections.linkedExecutionsDesc': 'Approvals and runs generated by this session.',
        'sessions.sections.timeline': 'Timeline',
        'sessions.sections.timelineDesc': 'High-level state transitions and operator-visible events.',
        'sessions.sections.audit': 'Audit trace',
        'sessions.sections.auditDesc': 'Backend audit entries tied to this session.',
        'sessions.fields.currentConclusion': 'Current conclusion',
        'sessions.fields.evidence': 'Evidence',
        'sessions.fields.risk': 'Risk level',
        'sessions.fields.nextStep': 'Next step',
        'sessions.fields.currentState': 'Current state',
        'sessions.evidence.metrics': 'Metrics',
        'sessions.evidence.logs': 'Logs',
        'sessions.evidence.traces': 'Traces',
        'sessions.evidence.delivery': 'Deploy / change',
        'sessions.evidence.ssh': 'SSH',
        'sessions.evidence.none': 'No evidence captured yet.',
        'sessions.evidence.attachments': '{{count}} evidence attachment available',
        'sessions.evidence.attachments_plural': '{{count}} evidence attachments available',
        'sessions.empty.delivery': 'No deploy or change evidence yet',
        'sessions.empty.deliveryDesc': 'No deploy, release, rollout, rollback, pipeline, or change-window evidence has been captured for this session.',
        'sessions.empty.ssh': 'No SSH evidence yet',
        'sessions.empty.sshDesc': 'No bastion or SSH access checks have been captured for this session.',
        'sessions.empty.description': 'Complete setup or trigger runtime checks to generate sessions',
        'sessions.empty.narrativeUnavailable': 'Diagnosis summary unavailable',
        'sessions.empty.narrativeUnavailableDesc': 'The long-form diagnosis narrative has not been generated yet. Use the current conclusion and evidence summary first.',
        'sessions.empty.traceUnavailable': 'Full trace unavailable',
        'sessions.empty.attachments': 'No attachments',
        'sessions.empty.attachmentsDesc': 'No image or file attachments were captured for this session.',
        'sessions.empty.notifications': 'No notifications recorded',
        'sessions.empty.notificationsDesc': 'No notification digests have been stored for this session yet.',
        'sessions.states.pendingEvidence': 'Pending evidence',
        'sessions.states.pendingEvidenceDesc': 'Metrics, logs, traces, and change evidence are still being gathered.',
        'sessions.states.pendingApproval': 'Pending approval',
        'sessions.states.pendingApprovalDesc': 'A proposed action is waiting for operator approval.',
        'sessions.states.executing': 'Executing',
        'sessions.states.executingDesc': 'The approved action is currently running.',
        'sessions.states.observing': 'Observing',
        'sessions.states.observingDesc': 'The action finished and the operator is watching verification evidence.',
        'sessions.states.manualIntervention': 'Needs human intervention',
        'sessions.states.manualInterventionDesc': 'The evidence is not enough to keep converging automatically, so the operator needs to take over directly.',
        'sessions.states.resolved': 'Resolved',
        'sessions.states.resolvedDesc': 'The session has enough evidence to be considered resolved.',
        'sessions.action.viewDocument': 'View document',
        'sessions.action.download': 'Download',
        'sessions.fields.checkedAt': 'Checked at {{time}}',
      }
      const template = table[key] ?? fallback ?? key
      if (!params) {
        return template
      }
      return template.replace(/\{\{(\w+)\}\}/g, (_, token: string) => String(params[token] ?? ''))
    },
  }),
}))

async function flushAll() {
  await act(async () => {
    await Promise.resolve()
    await new Promise((resolve) => setTimeout(resolve, 10))
  })
  await act(async () => {
    await Promise.resolve()
  })
}

describe('SessionDetailView', () => {
  beforeEach(() => {
    ;(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true
    fetchSessionMock.mockReset()
    fetchSessionTraceMock.mockReset()

    fetchSessionMock.mockResolvedValue({
      session_id: 'sess-1',
      status: 'analyzing',
      diagnosis_summary: 'Long narrative that explains how the operator investigated the issue step by step.',
      golden_summary: {
        headline: 'Checkout latency spike',
        conclusion: 'Checkout remains degraded because inventory CPU is saturated and downstream calls are timing out.',
        risk: 'critical',
        next_action: 'Throttle the inventory backfill job and page the inventory owner.',
        evidence: [
          'Metrics: checkout p95 latency rose from 600ms to 2.4s in 15 minutes.',
          'Logs: inventory-api timeout errors spiked across three pods.',
          'Traces: inventory-db spans now dominate the slow checkout requests.',
          'Delivery: Deploy checkout-api build 418 reached production canary before the latency spike.',
          'Delivery: Telegram alert reached the primary on-call target in 12 seconds.',
          'SSH: bastion ssh handshake to inventory-api-1 succeeded for manual fallback.',
        ],
      },
      tool_plan: [
        {
          tool: 'metrics.query',
          reason: 'Check checkout latency and inventory saturation',
          status: 'completed',
          output: { summary: 'inventory CPU is 92% and checkout p95 is 2.4s' },
        },
        {
          tool: 'logs.search',
          reason: 'Inspect inventory-api timeout errors',
          status: 'completed',
          output: { summary: 'timeout and context deadline exceeded errors increased 5x' },
        },
        {
          tool: 'traces.search',
          reason: 'Review slow checkout traces',
          status: 'completed',
          output: { summary: 'inventory-db spans account for 68% of end-to-end latency' },
        },
        {
          tool: 'deploy.inspect',
          reason: 'Check deploy pipeline and canary rollout status',
          status: 'completed',
          output: { summary: 'Build 418 passed the pipeline and advanced to 25% canary rollout.' },
        },
        {
          tool: 'notification.inspect',
          reason: 'Check telegram delivery receipts',
          status: 'completed',
          output: { summary: 'Inbox fallback delivery also succeeded for the backup target.' },
        },
        {
          tool: 'ssh.check',
          reason: 'Validate bastion ssh access before manual intervention',
          status: 'completed',
          output: { summary: 'SSH command execution path is available through the production bastion.' },
        },
      ],
      attachments: [
        {
          type: 'image',
          name: 'latency-chart.png',
          url: 'https://example.com/latency-chart.png',
        },
      ],
      alert: {
        labels: {
          service: 'checkout',
          instance: 'inventory-api-1',
          alertname: 'CheckoutLatencyHigh',
        },
      },
      verification: {
        status: 'pending',
        summary: 'Still collecting confirmation samples before calling the issue contained.',
      },
      notifications: [],
      executions: [],
      timeline: [
        {
          event: 'analysis_started',
          message: 'Diagnosis started',
          created_at: '2026-04-18T00:00:00Z',
        },
      ],
    })

    fetchSessionTraceMock.mockResolvedValue({
      session_id: 'sess-1',
      audit_entries: [
        {
          resource_type: 'session',
          resource_id: 'sess-1',
          action: 'analysis_started',
          created_at: '2026-04-18T00:00:00Z',
        },
      ],
      knowledge: {
        document_id: 'doc-1',
        title: 'Checkout runbook',
        summary: 'The runbook recommends verifying saturation before any restart.',
      },
    })
  })

  it('puts current diagnosis and evidence summary ahead of narrative and process-heavy sections', async () => {
    const { SessionDetailView } = await import('../src/pages/sessions/SessionDetail')
    const container = document.createElement('div')
    document.body.appendChild(container)
    const root = createRoot(container)
    const queryClient = new QueryClient({
      defaultOptions: {
        queries: {
          retry: false,
        },
      },
    })

    await act(async () => {
      root.render(
        <QueryClientProvider client={queryClient}>
          <MemoryRouter initialEntries={['/sessions/sess-1']}>
            <Routes>
              <Route path="/sessions/:id" element={<SessionDetailView />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      )
    })
    await flushAll()
    await flushAll()

    const text = container.textContent || ''
    expect(fetchSessionMock).toHaveBeenCalledWith('sess-1')
    expect(fetchSessionTraceMock).toHaveBeenCalledWith('sess-1')
    expect(text).toContain('Current diagnosis')
    expect(text).toContain('Current conclusion')
    expect(text).toContain('Evidence')
    expect(text).toContain('Risk level')
    expect(text).toContain('Next step')
    expect(text).toContain('Current state')
    expect(text).toContain('Evidence summary')
    expect(text).toContain('Metrics')
    expect(text).toContain('Logs')
    expect(text).toContain('Traces')
    expect(text).toContain('Deploy / change')
    expect(text).toContain('SSH')
    expect(text).toContain('Deploy checkout-api build 418 reached production canary before the latency spike.')
    expect(text).toContain('bastion ssh handshake to inventory-api-1 succeeded for manual fallback.')
    expect(text).toContain('1 evidence attachment available')
    expect(text.indexOf('Current diagnosis')).toBeLessThan(text.indexOf('Evidence summary'))
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('Diagnosis narrative'))
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('Tool plan'))
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('Timeline'))
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('Audit trace'))
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('Raw alert context'))

    await act(async () => {
      root.unmount()
    })
    queryClient.clear()
    container.remove()
  })

  it('keeps empty delivery and ssh evidence visible in the quick-scan area', async () => {
    fetchSessionMock.mockResolvedValueOnce({
      session_id: 'sess-2',
      status: 'analyzing',
      diagnosis_summary: '',
      golden_summary: {
        headline: 'Checkout signal still under review',
        conclusion: 'Need more evidence before escalation.',
        risk: 'warning',
        next_action: 'Continue collecting metrics and logs.',
        evidence: [],
      },
      tool_plan: [],
      attachments: [],
      alert: { labels: { service: 'checkout', instance: 'checkout-1', alertname: 'CheckoutLatencyHigh' } },
      verification: null,
      notifications: [],
      executions: [],
      timeline: [],
    })
    fetchSessionTraceMock.mockResolvedValueOnce({
      session_id: 'sess-2',
      audit_entries: [],
      knowledge: undefined,
    })

    const { SessionDetailView } = await import('../src/pages/sessions/SessionDetail')
    const container = document.createElement('div')
    document.body.appendChild(container)
    const root = createRoot(container)
    const queryClient = new QueryClient({
      defaultOptions: {
        queries: {
          retry: false,
        },
      },
    })

    await act(async () => {
      root.render(
        <QueryClientProvider client={queryClient}>
          <MemoryRouter initialEntries={['/sessions/sess-2']}>
            <Routes>
              <Route path="/sessions/:id" element={<SessionDetailView />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      )
    })
    await flushAll()
    await flushAll()

    const text = container.textContent || ''
    expect(text).toContain('Deploy / change')
    expect(text).toContain('SSH')
    expect(text).toContain('No deploy or change evidence yet')
    expect(text).toContain('No SSH evidence yet')
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('No deploy or change evidence yet'))
    expect(text.indexOf('Evidence summary')).toBeLessThan(text.indexOf('No SSH evidence yet'))

    await act(async () => {
      root.unmount()
    })
    queryClient.clear()
    container.remove()
  })
})
