package reasoning

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const defaultSystemPrompt = `You are TARS, an operations copilot.
Return ONLY strict JSON with fields: summary, execution_hint.
Do not use markdown, code fences, or extra prose.
summary must be concise and actionable.
execution_hint must be a single shell command candidate generated by the model itself.
The platform will handle authorization, approval, and execution policy after generation.
Treat tool results already present in context as the primary evidence source.
If observability, delivery, metrics, knowledge, or capability results already answer the request, use an empty execution_hint.
Do not generate generic shell commands to re-check systems that were already queried by platform tools.
Only provide a shell command when host-level evidence is still required after considering the tool evidence.
Treat routine read-only infrastructure questions as valid operational requests, including load, memory, disk, process, ports, hostname, service status, public/internal IP, MAC address, interface info, and routing.
For those requests, prefer a read-only shell command instead of refusing.
If no shell command is appropriate, use an empty string for execution_hint.`

const defaultUserPromptTemplate = `session_id={{ .SessionID }}
context={{ .ContextJSON }}`

type PromptSet struct {
	SystemPrompt       string
	UserPromptTemplate string
}

type PromptProvider interface {
	CurrentPromptSet() *PromptSet
}

type promptFileConfig struct {
	Reasoning struct {
		SystemPrompt       string `yaml:"system_prompt"`
		UserPromptTemplate string `yaml:"user_prompt_template"`
	} `yaml:"reasoning"`
}

type promptTemplateData struct {
	SessionID   string
	Context     map[string]interface{}
	ContextJSON string
}

func LoadPromptSet(path string) (*PromptSet, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	return ParsePromptSet(content)
}

func ParsePromptSet(content []byte) (*PromptSet, error) {

	var cfg promptFileConfig
	if err := yaml.Unmarshal(content, &cfg); err != nil {
		return nil, err
	}

	return NewPromptSet(cfg.Reasoning.SystemPrompt, cfg.Reasoning.UserPromptTemplate), nil
}

func NewPromptSet(systemPrompt string, userPromptTemplate string) *PromptSet {
	systemPrompt = strings.TrimSpace(systemPrompt)
	if systemPrompt == "" {
		systemPrompt = defaultSystemPrompt
	}

	userPromptTemplate = strings.TrimSpace(userPromptTemplate)
	if userPromptTemplate == "" {
		userPromptTemplate = defaultUserPromptTemplate
	}

	return &PromptSet{
		SystemPrompt:       systemPrompt,
		UserPromptTemplate: userPromptTemplate,
	}
}

func DefaultPromptSet() *PromptSet {
	return NewPromptSet("", "")
}

func EncodePromptSet(p *PromptSet) (string, error) {
	set := DefaultPromptSet()
	if p != nil {
		set = NewPromptSet(p.SystemPrompt, p.UserPromptTemplate)
	}

	var cfg promptFileConfig
	cfg.Reasoning.SystemPrompt = set.SystemPrompt
	cfg.Reasoning.UserPromptTemplate = set.UserPromptTemplate

	content, err := yaml.Marshal(cfg)
	if err != nil {
		return "", err
	}
	return string(content), nil
}

func (p *PromptSet) RenderUserPrompt(sessionID string, context map[string]interface{}) (string, error) {
	if p == nil {
		p = DefaultPromptSet()
	}

	contextJSON, err := json.Marshal(context)
	if err != nil {
		return "", err
	}

	tmpl, err := template.New("reasoning-user-prompt").Option("missingkey=zero").Parse(p.UserPromptTemplate)
	if err != nil {
		return "", err
	}

	var rendered bytes.Buffer
	if err := tmpl.Execute(&rendered, promptTemplateData{
		SessionID:   sessionID,
		Context:     context,
		ContextJSON: string(contextJSON),
	}); err != nil {
		return "", err
	}

	return rendered.String(), nil
}

func (p *PromptSet) CurrentPromptSet() *PromptSet {
	return defaultPromptSet(p)
}
